### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Ypot** [Stebalien/org-capture-extension#1]
Hi!

I have installed it, but I don't know how to use it. 
Supposing everything works correctly, could you please share some basic instuctions to capture the web?

Thanks

**Comment by Stebalien** [comment]
1. Setup hotkeys as described in https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox.
2. Setup org-protocol as described in https://orgmode.org/worg/org-contrib/org-protocol.html.
3. Make sure the templates configured in this extension match the templates you've configured in `org-capture`.

Without having more of a sense of where you're stuck, I'm not sure where to start with the documentation.

**Comment by Ypot** [comment]
1 and 2 I think are ok.
I wasn't able to understand how the templates must match. Could be appropriate to make a new org-capture template that works with the extension? Any simple instruction?

**Comment by Stebalien** [comment]
The template hotkey in the extension's config needs to match the template hotkey specified in your org-capture templates. You don't _need_ any extension-specific templates, just a template compatible with org-protocol (see https://orgmode.org/worg/org-contrib/org-protocol.html#orgb58ea46)

**Comment by Ypot** [comment]
Sorry, I don't know how to activate the org-capture template. I don't understand neither this dialog:

![imagen](https://github.com/Stebalien/org-capture-extension/assets/30699014/7a2fcd94-e5c0-4297-aa1f-b3bc675a5f65)

This is my template, for the "x" hotkey:
(setq org-capture-templates
      (quote
       (("x"
         "org-protocol template"
         entry
         (file+headline "~/2-Areas_R/NOTAS/1-TAREAS.org" "Notes")
         "* %^{Title}\n\n  Source: %u, %c\n\n  %i"
         :empty-lines 1)
        ;; ... more templates here ...
        )))

**Comment by Stebalien** [comment]
Ah, you can:

1. Right-click on the page.
2. Right click on the tab.
3. Configure a hotkey as described in https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox.
4. Click on the extension's "action" button (your default is set to capture).

If the your org-protocol is setup correctly, it should "just work".

**Comment by Ypot** [comment]
Thanks
It doesn't, it just copies the web link :/

But the installation verification of org-protocol launches the template:
Verify the installation
After your protocol is registered with your browser/OS, these links here should work. Click on them and see if emacs reacts:
...
Org capture (select some text if you like)
...
https://orgmode.org/worg/org-contrib/org-protocol.html#orga803029

**Comment by Stebalien** [comment]
>  It doesn't, it just copies the web link :/

You mean captures it with `org-store-link`? How are you activating it (context menu, hot key, etc)?

**Comment by Ypot** [comment]
Context menu:
Greedy org-protocol handler.  Killing client.
No server buffers remain to edit
Link copied
SVG tag mode on [2 times]

Extension button:
Greedy org-protocol handler.  Killing client.
No server buffers remain to edit
Link copied

Hotkey:
Greedy org-protocol handler.  Killing client.
No server buffers remain to edit
Link copied

**Comment by Stebalien** [comment]
Looks related to https://stackoverflow.com/questions/47647948/getting-org-protocol-to-work-on-firefox-quantum-no-server-buffers-remain-to?

I see:

> Greedy org-protocol handler.  Killing client.
> No server buffers remain to edit
> Clipboard pasted as level 1 subtree
> Item captured.

Interestingly, when I specify the wrong "key", I see:

> No capture template referred to by "x" keys

In my messages, so that's not the issue.

---

What emacs/org-mode version are you using?

**Comment by Ypot** [comment]
Hi, these are my versions:

GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13
Org mode version 9.6.7 
Windows 10

**Comment by Stebalien** [comment]
Ok, it looks like you're using `org-super-links`. Could you try turning that off? That's where the "Link copied" message is coming from.

**Comment by Ypot** [comment]
Hi
Now I receive this message:

Greedy org-protocol handler.  Killing client.
No server buffers remain to edit
SVG tag mode on [2 times]

**Comment by Stebalien** [comment]
What if you try specifying the _wrong_ key for the template. I.e., "z" instead of "x". I'd expect to see an error like:

> No capture template referred to by "z" keys

**Comment by Stebalien** [comment]
Specifically, _don't_ change the key in emacs. Just change the "template" field in the addon. We're trying to get firefox to pass the wrong template key to emacs.
